In [1]:
import json
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("../india_weather_rainfall_data.xlsx")
df

,date_of_record,month,season,station_name,state,district,avg_temp,min_temp,max_temp,wind_speed,air_pressure,elevation,latitude,longitude,rainfall
0,2021-01-02,January,Winter,Gulmarg,JK,Baramulla,-2.2,-6.6,-0.8,2.2,1020.0,2652,34.0500,74.4000,0.1
1,2021-01-03,January,Winter,Gulmarg,JK,Baramulla,-3.6,-4.6,-1.8,3.7,1019.5,2652,34.0500,74.4000,4.4
2,2021-01-04,January,Winter,Gulmarg,JK,Baramulla,-3.0,-4.5,-1.1,2.1,1022.0,2652,34.0500,74.4000,2.3
3,2021-01-05,January,Winter,Gulmarg,JK,Baramulla,-3.3,-5.1,-1.2,2.8,1015.6,2652,34.0500,74.4000,35.0
4,2021-01-06,January,Winter,Gulmarg,JK,Baramulla,-3.9,-8.3,-1.0,3.4,1015.3,2652,34.0500,74.4000,25.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970334,2025-02-06,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,27.3,22.0,34.0,7.6,1011.4,5,17.7167,83.2333,0.0
970335,2025-02-07,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.7,23.0,30.0,7.7,1013.1,5,17.7167,83.2333,0.3
970336,2025-02-08,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.5,23.0,30.0,8.7,1013.0,5,17.7167,83.2333,0.0
970337,2025-02-09,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.5,23.0,30.0,8.5,1012.8,5,17.7167,83.2333,0.0
970338,2025-02-10,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,25.5,21.8,31.0,8.2,1013.9,5,17.7167,83.2333,0.0

In [3]:
# df = df.replace({np.nan: None})

In [4]:
df['date_of_record'] = df['date_of_record'].astype('str')

In [5]:
for col in df.select_dtypes(include=['datetime64[ns]']):
    df[col] = df[col].astype(str)

In [6]:
missing_values = {}
null_count = df.isnull().sum()
for n, i in enumerate(null_count):
    missing_values[df.columns[n]] = 100 - (df.shape[0] - i)/df.shape[0]*100

missing_values

{'date_of_record': 0.0,
 'month': 0.0,
 'season': 0.0,
 'station_name': 0.0,
 'state': 0.0,
 'district': 0.0,
 'avg_temp': 0.0,
 'min_temp': 4.523985947179284,
 'max_temp': 11.3978722899935,
 'wind_speed': 28.283311296361376,
 'air_pressure': 31.397686787813328,
 'elevation': 0.0,
 'latitude': 0.0,
 'longitude': 0.0,
 'rainfall': 26.542682505804677}

In [7]:
def district_groupwise_data(target):
    district_avg_temp_dict = df.groupby(['state','district'])[target].mean().reset_index().to_dict(orient='records')
    district_avg_temp = {}

    for i in district_avg_temp_dict:
        if i['state'] not in district_avg_temp:
            district_avg_temp[i['state']] = {}

        district_avg_temp[i['state']][i['district']] = i[target]

    return district_avg_temp

In [8]:
def station_groupwise_data(target):
    station_avg_temp_dict = df.groupby(['state','district','station_name'])[target].mean().reset_index().to_dict(orient='records')
    station_avg_temp = {}

    for i in station_avg_temp_dict:
        if i['state'] not in station_avg_temp:
            station_avg_temp[i['state']] = {}

        if i['district'] not in station_avg_temp[i['state']]:
            station_avg_temp[i['state']][i['district']] = {}

        station_avg_temp[i['state']][i['district']][i['station_name']] = i[target]

    return station_avg_temp

In [9]:
def season_groupwise_data(target):
    season_avg_temp_dict = df.groupby(['state','district','station_name', 'season'])[target].mean().reset_index().to_dict(orient='records')
    season_avg_temp = {}

    for i in season_avg_temp_dict:
        if i['state'] not in season_avg_temp:
            season_avg_temp[i['state']] = {}

        if i['district'] not in season_avg_temp[i['state']]:
            season_avg_temp[i['state']][i['district']] = {}

        if i['station_name'] not in season_avg_temp[i['state']][i['district']]:
                season_avg_temp[i['state']][i['district']][i['station_name']] = {}

        season_avg_temp[i['state']][i['district']][i['station_name']][i['season']] = i[target]

    return season_avg_temp

In [10]:
count = list(np.histogram(df['avg_temp'], bins=1000))

In [11]:
df = df.dropna(subset=['date_of_record'])
df['date_of_record'] = pd.to_datetime(df['date_of_record'])
df['max_temp'] = df['max_temp'].fillna(df.groupby(['month', 'station_name'])['max_temp'].transform('mean'))
df['max_temp'] = df['max_temp'].fillna(df['max_temp'].median())
df['min_temp'] = df['min_temp'].fillna(df.groupby(['month', 'station_name'])['min_temp'].transform('mean'))
df['min_temp'] = df['min_temp'].fillna(df['min_temp'].median())
df['wind_speed'] = df['wind_speed'].fillna(df.groupby(['month', 'station_name'])['wind_speed'].transform('mean'))
df['wind_speed'] = df['wind_speed'].fillna(df['wind_speed'].median())
df['air_pressure'] = df['air_pressure'].fillna(df.groupby(['month', 'station_name'])['air_pressure'].transform('mean'))
df['air_pressure'] = df['air_pressure'].fillna(df['air_pressure'].median())
df['rainfall'] = df['rainfall'].fillna(df.groupby(['month', 'station_name'])['rainfall'].transform('mean'))
df['rainfall'] = df['rainfall'].fillna(df['rainfall'].median())

df = df.drop_duplicates()

In [12]:
temp_series = df.groupby('date_of_record')['avg_temp'].mean()
min_temp_series = df.groupby('date_of_record')['min_temp'].mean()
max_temp_series = df.groupby('date_of_record')['max_temp'].mean()
wind_speed_series = df.groupby('date_of_record')['wind_speed'].mean()
air_pressure_series = df.groupby('date_of_record')['air_pressure'].mean()
rainfall_series = df.groupby('date_of_record')['rainfall'].mean()

In [13]:
df_sample = df.sample(10000)
df_sample['date_of_record'] = df_sample['date_of_record'].astype('str')

In [14]:
df_state_sample = df.groupby('state', group_keys=False)\
    .apply(lambda x: x.sample(min(len(x), 500)))\
    .reset_index(drop=True)

df_season_sample = df.groupby('season', group_keys=False).apply(lambda x: x.sample(min(len(x), 500))).reset_index(drop=True)
df_state_sample['date_of_record'] = df_state_sample['date_of_record'].astype(str)
df_season_sample['date_of_record'] = df_season_sample['date_of_record'].astype(str)

/var/folders/7c/lq4bm735423dshfysxglzw080000gn/T/ipykernel_41577/2441362625.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(min(len(x), 500)))\
/var/folders/7c/lq4bm735423dshfysxglzw080000gn/T/ipykernel_41577/2441362625.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_season_sample = df.groupby('season', group_keys=False).apply(lambda x: x.sample(min(len(x), 500))).reset_index(drop=True)

In [15]:
def outlier_stats(series):
    q1 = series.quantile(0.25)
    q3 = series.quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    return {
        "q1": float(q1),
        "q3": float(q3),
        "median": float(series.median()),
        "lower": float(lower),
        "upper": float(upper),
        "outliers": int(((series < lower) | (series > upper)).sum())
    }

In [16]:
corr = df.corr(numeric_only=True)

In [17]:
target_corr = df.corr(numeric_only=True)['avg_temp'].drop('avg_temp').sort_values(ascending=False)
target_corr

min_temp        0.917605
max_temp        0.916885
wind_speed      0.300535
rainfall        0.028063
longitude      -0.054895
latitude       -0.296831
elevation      -0.439126
air_pressure   -0.703504
Name: avg_temp, dtype: float64

In [18]:
monthly_trend = df.groupby('month').agg({
    'avg_temp': 'mean',
    'max_temp': 'mean',
    'min_temp': 'mean',
    'wind_speed': 'mean',
    'air_pressure': 'mean',
    'rainfall': 'mean',
}).reset_index(drop=False)
month_map = {
    'January': 1,
    'February': 2,
    'March': 3,
    'April': 4,
    'May': 5,
    'June': 6,
    'July': 7,
    'August': 8,
    'September': 9,
    'October': 10,
    'November': 11,
    'December': 12,
}
monthly_trend['weight'] = monthly_trend['month'].map(month_map)
monthly_trend = monthly_trend.sort_values(by='weight')
monthly_trend = monthly_trend.drop(columns=['weight'])
monthly_trend

,month,avg_temp,max_temp,min_temp,wind_speed,air_pressure,rainfall
4,January,19.594499,25.952087,13.943598,8.122101,1014.790235,1.014606
3,February,22.235994,28.973097,15.800750,8.671941,1013.847241,0.660825
7,March,25.979654,32.661373,19.515909,8.973912,1011.397551,1.137699
0,April,29.100049,35.574809,22.894483,9.718318,1008.588867,1.726433
8,May,30.315485,36.115868,24.791723,10.894192,1005.709215,4.080872
6,June,29.544730,34.562546,25.246434,11.772121,1003.815032,8.087275
5,July,27.781627,31.694675,24.610366,12.073179,1003.260618,12.317639
1,August,27.437673,31.355166,24.234667,11.036327,1004.956750,9.633181
11,September,27.236874,31.508012,23.719059,9.563714,1006.333182,8.752536
10,October,26.124751,31.468095,21.415806,7.360877,1010.517785,4.822965
9,November,23.287213,29.327904,17.903246,7.427652,1013.199793,2.655262
2,December,20.525492,26.770252,15.099945,7.863257,1014.649755,1.800213

In [19]:
stat = df.describe().reset_index().to_dict(orient='records')
for idx, row in enumerate(stat):
    for k, v in row.items():
        if isinstance(v, pd.Timestamp):
            stat[idx][k] = str(v)
        if pd.isna(v):
            stat[idx][k] = None

In [20]:
kpi_data = {}

state_values = df.groupby(['state']).agg({
    'avg_temp' : 'mean',
    'min_temp' : 'mean',
    'max_temp' : 'mean',
    'wind_speed' : 'mean',
    'air_pressure' : 'mean',
    'rainfall' : 'mean',
}).reset_index().to_dict(orient='records')

for i in state_values:
    kpi_data[i['state']] = {
        'avg_temp': i['avg_temp'],
        'min_temp': i['min_temp'],
        'max_temp': i['max_temp'],
        'wind_speed': i['wind_speed'],
        'air_pressure': i['air_pressure'],
        'rainfall': i['rainfall'],
        'district': {}
    }

district_values = df.groupby(['state', 'district']).agg({
    'avg_temp' : 'mean',
    'min_temp' : 'mean',
    'max_temp' : 'mean',
    'wind_speed' : 'mean',
    'air_pressure' : 'mean',
    'rainfall' : 'mean',
}).reset_index().to_dict(orient='records')

for i in district_values:
    kpi_data[i['state']]['district'][i['district']] = {
        'avg_temp': i['avg_temp'],
        'min_temp': i['min_temp'],
        'max_temp': i['max_temp'],
        'wind_speed': i['wind_speed'],
        'air_pressure': i['air_pressure'],
        'rainfall': i['rainfall'],
        'station_name': {}
    }

station_values = df.groupby(['state', 'district', 'station_name']).agg({
    'avg_temp' : 'mean',
    'min_temp' : 'mean',
    'max_temp' : 'mean',
    'wind_speed' : 'mean',
    'air_pressure' : 'mean',
    'rainfall' : 'mean',
}).reset_index().to_dict(orient='records')

for i in station_values:
    kpi_data[i['state']]['district'][i['district']]['station_name'][i['station_name']] = {
        'avg_temp': i['avg_temp'],
        'min_temp': i['min_temp'],
        'max_temp': i['max_temp'],
        'wind_speed': i['wind_speed'],
        'air_pressure': i['air_pressure'],
        'rainfall': i['rainfall'],
        'season': {}
    }

season_values = df.groupby(['state', 'district', 'station_name', 'season']).agg({
    'avg_temp' : 'mean',
    'min_temp' : 'mean',
    'max_temp' : 'mean',
    'wind_speed' : 'mean',
    'air_pressure' : 'mean',
    'rainfall' : 'mean',
}).reset_index().to_dict(orient='records')

for i in season_values:
    kpi_data[i['state']]['district'][i['district']]['station_name'][i['station_name']]['season'][i['season']] = {
        'avg_temp': i['avg_temp'],
        'min_temp': i['min_temp'],
        'max_temp': i['max_temp'],
        'wind_speed': i['wind_speed'],
        'air_pressure': i['air_pressure'],
        'rainfall': i['rainfall'],
    }

kpi_data

{'AN': {'avg_temp': 27.4089872486513,
  'min_temp': 25.1610276284994,
  'max_temp': 29.996525359599392,
  'wind_speed': 15.06648400353709,
  'air_pressure': 1009.5592079625159,
  'rainfall': 7.3986748322369085,
  'district': {'Nicobar': {'avg_temp': 27.506747366061422,
    'min_temp': 25.755189419412687,
    'max_temp': 29.264066352835687,
    'wind_speed': 18.032369423895986,
    'air_pressure': 1009.760031383098,
    'rainfall': 6.584263618022865,
    'station_name': {'Car Nicobar': {'avg_temp': 27.472158708809683,
      'min_temp': 25.51698049764627,
      'max_temp': 29.33883658372562,
      'wind_speed': 18.049731002017484,
      'air_pressure': 1009.7239744451917,
      'rainfall': 6.576529926025555,
      'season': {'Monsoon': {'avg_temp': 27.44888888888889,
        'min_temp': 25.990277777777777,
        'max_temp': 29.068472222222223,
        'wind_speed': 23.02611111111111,
        'air_pressure': 1008.7658333333334,
        'rainfall': 8.501249999999999},
       'Post-monsoon': {'avg_temp': 26.918032786885245,
        'min_temp': 25.197540983606558,
        'max_temp': 28.688114754098358,
        'wind_speed': 14.571926229508197,
        'air_pressure': 1009.9920081967213,
        'rainfall': 9.507377049180329},
       'Summer': {'avg_temp': 28.39060773480663,
        'min_temp': 26.573066298342543,
        'max_temp': 30.604143646408843,
        'wind_speed': 16.323342541436464,
        'air_pressure': 1008.7441988950277,
        'rainfall': 6.462016574585635},
       'Winter': {'avg_temp': 27.109596928982725,
        'min_temp': 24.605758157389637,
        'max_temp': 28.951247600767754,
        'wind_speed': 17.439443378119,
        'air_pressure': 1010.9412667946258,
        'rainfall': 3.953550863723609}}},
     'Nancowry': {'avg_temp': 27.575924680564896,
      'min_temp': 26.23160726294553,
      'max_temp': 29.11452589105582,
      'wind_speed': 17.997646267652993,
      'air_pressure': 1009.8321452589105,
      'rainfall': 6.599731002017484,
      'season': {'Monsoon': {'avg_temp': 27.459166666666665,
        'min_temp': 26.093888888888888,
        'max_temp': 28.834444444444443,
        'wind_speed': 22.68638888888889,
        'air_pressure': 1009.2563888888889,
        'rainfall': 7.727777777777778},
       'Post-monsoon': {'avg_temp': 26.93565573770492,
        'min_temp': 25.60327868852459,
        'max_temp': 28.500819672131147,
        'wind_speed': 14.507377049180329,
        'air_pressure': 1010.1,
        'rainfall': 9.692213114754098},
       'Summer': {'avg_temp': 28.270165745856353,
        'min_temp': 26.81961325966851,
        'max_temp': 29.923756906077347,
        'wind_speed': 16.21243093922652,
        'air_pressure': 1009.0685082872927,
        'rainfall': 6.343093922651933},
       'Winter': {'avg_temp': 27.47408829174664,
        'min_temp': 26.212476007677544,
        'max_temp': 29.03320537428023,
        'wind_speed': 17.632821497120922,
        'air_pressure': 1010.6351247600768,
        'rainfall': 4.550287907869482}}}}},
   'North & Middle Andaman': {'avg_temp': 27.222950268817204,
    'min_temp': 25.36334005376344,
    'max_temp': 29.553192204301077,
    'wind_speed': 16.397379032258065,
    'air_pressure': 1009.6306115591399,
    'rainfall': 5.673857526881721,
    'station_name': {'Long Island': {'avg_temp': 26.753629032258065,
      'min_temp': 24.381586021505377,
      'max_temp': 29.714919354838713,
      'wind_speed': 14.955712365591397,
      'air_pressure': 1009.5911962365591,
      'rainfall': 6.044690860215054,
      'season': {'Monsoon': {'avg_temp': 26.634166666666665,
        'min_temp': 24.926388888888887,
        'max_temp': 29.089166666666667,
        'wind_speed': 18.214166666666667,
        'air_pressure': 1007.796111111111,
        'rainfall': 10.459166666666667},
       'Post-monsoon': {'avg_temp': 26.348360655737704,
        'min_temp': 24.38360655737705,
        'max_temp': 29.01065573770492,
        'wind_speed': 13.107377049180327,
        'air_pressure': 1009.9909836065573,
        'rainfall': 8.020081967213114},
       'Summer': {'avg_temp': 27.90497237569061,
        'min_temp': 25.445027624309393,
        'max_temp': 30.966574585635357,
        'wind_speed': 13.86049723756906,
        'air_pressure': 1008.2638121546961,
        'rainfall': 6.751381215469613},
       'Winter': {'avg_temp': 26.227011494252874,
        'min_temp': 23.267432950191573,
        'max_temp': 29.607662835249045,
        'wind_speed': 14.33199233716475,
        'air_pressure': 1011.5628352490422,
        'rainfall': 1.5867816091954021}}},
     'Maya Bandar': {'avg_temp': 27.692271505376343,
      'min_temp': 26.345094086021504,
      'max_temp': 29.39146505376344,
      'wind_speed': 17.839045698924732,
      'air_pressure': 1009.6700268817204,
      'rainfall': 5.303024193548387,
      'season': {'Monsoon': {'avg_temp': 27.491666666666667,
        'min_temp': 26.1475,
        'max_temp': 29.1475,
        'wind_speed': 21.3075,
        'air_pressure': 1007.6969444444445,
        'rainfall': 9.415000000000001},
       'Post-monsoon': {'avg_temp': 27.651639344262296,
        'min_temp': 26.467622950819674,
        'max_temp': 28.908196721311477,
        'wind_speed': 16.31516393442623,
        'air_pressure': 1010.0799180327868,
        'rainfall': 7.392622950819672},
       'Summer': {'avg_temp': 28.58204419889503,
        'min_temp': 27.09889502762431,
        'max_temp': 30.687292817679555,
        'wind_speed': 16.66049723756906,
        'air_pressure': 1008.2997237569061,
        'rainfall': 5.329281767955801},
       'Winter': {'avg_temp': 27.232567049808427,
        'min_temp': 25.90134099616858,
        'max_temp': 28.886973180076627,
        'wind_speed': 16.97662835249042,
        'air_pressure': 1011.7894636015325,
        'rainfall': 1.4722222222222223}}}}},
   'South Andaman': {'avg_temp': 27.42223098591549,
    'min_temp': 24.794533259276875,
    'max_temp': 30.5133545538913,
    'wind_speed': 13.129406993317971,
    'air_pressure': 1009.4343211588236,
    'rainfall': 8.386409449402642,
    'station_name': {'Hut Bay': {'avg_temp': 26.90941492938803,
      'min_temp': 24.965635507733694,
      'max_temp': 29.46193678547411,
      'wind_speed': 17.575857431069267,
      'air_pressure': 1009.7351714862139,
      'rainfall': 6.6103564223268325,
      'season': {'Monsoon': {'avg_temp': 26.792222222222225,
        'min_temp': 25.208055555555553,
        'max_temp': 28.87611111111111,
        'wind_speed': 23.1725,
        'air_pressure': 1008.4927777777779,
        'rainfall': 9.979166666666666},
       'Post-monsoon': {'avg_temp': 26.216803278688523,
        'min_temp': 24.471721311475413,
        'max_temp': 28.78483606557377,
        'wind_speed': 14.154508196721311,
        'air_pressure': 1010.0061475409836,
        'rainfall': 9.708606557377049},
       'Summer': {'avg_temp': 27.87154696132597,
        'min_temp': 25.778176795580112,
        'max_temp': 30.44585635359116,
        'wind_speed': 16.629834254143645,
        'air_pressure': 1008.6991712707181,
        'rainfall': 6.902209944751381},
       'Winter': {'avg_temp': 26.646257197696738,
        'min_temp': 24.464875239923227,
        'max_temp': 29.500191938579654,
        'wind_speed': 15.968330134357005,
        'air_pressure': 1011.186564299424,
        'rainfall': 2.628790786948177}}},
     'Port Blair': {'avg_temp': 27.37301028695181,
      'min_temp': 24.58202096334415,
      'max_temp': 30.74772011702506,
      'wind_speed': 12.565727358208886,
      'air_pressure': 1009.5724375407802,
      'rainfall': 9.169521153399629,
      'season': {'Monsoon': {'avg_temp': 26.9629347826087,
        'min_temp': 24.6515781748746,
        'max_temp': 29.896522235068392,
        'wind_speed': 16.45912200149925,
        'air_pressure': 1008.0371770364817,
        'rainfall': 13.791378580868587},
       'Post-monsoon': {'avg_temp': 27.244754098360655,
        'min_temp': 24.673532098610938,
        'max_temp': 30.510549257693842,
        'wind_speed': 10.25450819672131,
        'air_pressure': 1009.9618852459016,
        'rainfall': 9.594242121497121},
       'Summer': {'avg_temp': 28.195384615384615,
        'min_temp': 25.283010487486237,
        'max_temp': 31.8214223398174,
        'wind_speed': 11.974175824175823,
        'air_pressure': 1008.3771978021978,
        'rainfall': 10.666546503823911},
       'Winter': {'avg_temp': 27.13947368421053,
        'min_temp': 23.977782610800247,
        'max_temp': 30.708411706220563,
        'wind_speed': 11.26288247196516,
        'air_pressure': 1011.3766996826787,
        'rainfall': 4.485723950291966}}},
     'Port Blair / Portblair / Austin?b?d': {'avg_temp': 27.677883053600436,
      'min_temp': 24.938169257576874,
      'max_temp': 30.70223160625195,
      'wind_speed': 11.903191717507683,
      'air_pressure': 1009.1750990820025,
      'rainfall': 8.318238419813268,
      'season': {'Monsoon': {'avg_temp': 27.36586956521739,
        'min_temp': 25.18575532715614,
        'max_temp': 30.17094341477048,
        'wind_speed': 14.863329897551225,
        'air_pressure': 1007.5783605072464,
        'rainfall': 12.239808631815531},
       'Post-monsoon': {'avg_temp': 27.494918032786888,
        'min_temp': 25.006800954645406,
        'max_temp': 30.387889171206826,
        'wind_speed': 9.577459016393442,
        'air_pressure': 1009.514344262295,
        'rainfall': 9.865087959339423},
       'Summer': {'avg_temp': 28.495604395604396,
        'min_temp': 25.689976982996377,
        'max_temp': 31.65323174479893,
        'wind_speed': 11.557142857142857,
        'air_pressure': 1008.018956043956,
        'rainfall': 9.605565437741149},
       'Winter': {'avg_temp': 27.402392344497606,
        'min_temp': 24.177571530817314,
        'max_temp': 30.554802495775654,
        'wind_speed': 11.113936761344702,
        'air_pressure': 1011.0205138295458,
        'rainfall': 3.7545299664899767}}}}}}},
 'AP': {'avg_temp': 27.841558505589862,
  'min_temp': 23.21099193145298,
  'max_temp': 33.434367347602084,
  'wind_speed': 9.999452131344635,
  'air_pressure': 1008.7940692891225,
  'rainfall': 3.670166542057175,
  'district': {'Bapatla': {'avg_temp': 27.825613496932515,
    'min_temp': 24.24792944785276,
    'max_temp': 32.247315950920246,
    'wind_speed': 11.534662576687117,
    'air_pressure': 1008.339800613497,
    'rainfall': 3.7057515337423315,
    'station_name': {'Bapatla': {'avg_temp': 27.825613496932515,
      'min_temp': 24.24792944785276,
      'max_temp': 32.247315950920246,
      'wind_speed': 11.534662576687117,
      'air_pressure': 1008.339800613497,
      'rainfall': 3.7057515337423315,
      'season': {'Monsoon': {'avg_temp': 28.981126760563377,
        'min_temp': 25.90450704225352,
        'max_temp': 33.06450704225352,
        'wind_speed': 11.94056338028169,
        'air_pressure': 1004.2281690140845,
        'rainfall': 6.549859154929577},
       'Post-monsoon': {'avg_temp': 26.89016393442623,
        'min_temp': 23.497131147540983,
        'max_temp': 31.02786885245902,
        'wind_speed': 9.297540983606558,
        'air_pressure': 1010.0803278688525,
        'rainfall': 5.081147540983606},
       'Summer': {'avg_temp': 30.988191881918816,
        'min_temp': 27.418081180811807,
        'max_temp': 35.5690036900369,
        'wind_speed': 13.64981549815498,
        'air_pressure': 1005.2335793357934,
        'rainfall': 2.451291512915129},
       'Winter': {'avg_temp': 25.431566820276498,
        'min_temp': 21.335483870967742,
        'max_temp': 30.190322580645162,
        'wind_speed': 11.13963133640553,
        'air_pressure': 1012.6640552995392,
        'rainfall': 1.3894009216589862}}}}},
   'Bhadradri Kothagudem': {'avg_temp': 27.585090664875754,
    'min_temp': 22.886165211551376,
    'max_temp': 33.44647414372062,
    'wind_speed': 7.565614506380121,
    'air_pressure': 1008.5547347212895,
    'rainfall': 3.5484217595701817,
    'station_name': {'Kothagudem': {'avg_temp': 27.585090664875754,
      'min_temp': 22.886165211551376,
      'max_temp': 33.44647414372062,
      'wind_speed': 7.565614506380121,
      'air_pressure': 1008.5547347212895,
      'rainfall': 3.5484217595701817,
      'season': {'Monsoon': {'avg_temp': 27.701944444444447,
        'min_temp': 24.905277777777776,
        'max_temp': 31.790833333333335,
        'wind_speed': 9.190277777777778,
        'air_pressure': 1004.1222222222223,
        'rainfall': 10.320277777777779},
       'Post-monsoon': {'avg_temp': 26.425,
        'min_temp': 22.090983606557376,
        'max_temp': 31.846721311475413,
        'wind_speed': 6.150819672131147,
        'air_pressure': 1010.7209016393442,
        'rainfall': 1.7561475409836065},
       'Summer': {'avg_temp': 31.105801104972375,
        'min_temp': 26.25414364640884,
        'max_temp': 37.54088397790055,
        'wind_speed': 8.261049723756907,
        'air_pressure': 1005.4116022099447,
        'rainfall': 2.32707182320442},
       'Winter': {'avg_temp': 25.608986615678777,
        'min_temp': 19.536137667304015,
        'max_temp': 32.49847036328872,
        'wind_speed': 6.626003824091779,
        'air_pressure': 1012.7707456978967,
        'rainfall': 0.568642447418738}}}}},
   'East Godavari': {'avg_temp': 28.231384408602153,
    'min_temp': 23.73313172043011,
    'max_temp': 33.82997311827957,
    'wind_speed': 11.15497311827957,
    'air_pressure': 1008.3030913978495,
    'rainfall': 3.943010752688172,
    'station_name': {'Rajahmundry / R?j?nagaram': {'avg_temp': 28.231384408602153,
      'min_temp': 23.73313172043011,
      'max_temp': 33.82997311827957,
      'wind_speed': 11.15497311827957,
      'air_pressure': 1008.3030913978495,
      'rainfall': 3.943010752688172,
      'season': {'Monsoon': {'avg_temp': 28.76888888888889,
        'min_temp': 25.436666666666667,
        'max_temp': 32.87777777777778,
        'wind_speed': 13.084166666666667,
        'air_pressure': 1003.6133333333333,
        'rainfall': 10.090277777777779},
       'Post-monsoon': {'avg_temp': 27.543032786885245,
        'min_temp': 23.22295081967213,
        'max_temp': 33.12622950819672,
        'wind_speed': 10.385245901639344,
        'air_pressure': 1010.2159836065574,
        'rainfall': 3.070901639344262},
       'Summer': {'avg_temp': 31.47582417582418,
        'min_temp': 26.77142857142857,
        'max_temp': 37.496153846153845,
        'wind_speed': 11.526648351648351,
        'air_pressure': 1005.3282967032967,
        'rainfall': 2.966483516483516},
       'Winter': {'avg_temp': 25.911153846153844,
        'min_temp': 20.666346153846153,
        'max_temp': 32.25307692307692,
        'wind_speed': 9.920384615384616,
        'air_pressure': 1012.7346153846154,
        'rainfall': 0.78}}}}},
   'Guntur': {'avg_temp': 28.472666218938887,
    'min_temp': 23.7632639355272,
    'max_temp': 34.30147750167898,
    'wind_speed': 9.692209536601746,
    'air_pressure': 1008.4098723975823,
    'rainfall': 2.7319006044325054,
    'station_name': {'Rentachintala': {'avg_temp': 28.472666218938887,
      'min_temp': 23.7632639355272,
      'max_temp': 34.30147750167898,
      'wind_speed': 9.692209536601746,
      'air_pressure': 1008.4098723975823,
      'rainfall': 2.7319006044325054,
      'season': {'Monsoon': {'avg_temp': 28.737222222222222,
        'min_temp': 25.63583333333333,
        'max_temp': 33.08638888888889,
        'wind_speed': 11.946111111111112,
        'air_pressure': 1004.396388888889,
        'rainfall': 6.724722222222223},
       'Post-monsoon': {'avg_temp': 26.690573770491802,
        'min_temp': 22.585245901639347,
        'max_temp': 31.78073770491803,
        'wind_speed': 7.19016393442623,
        'air_pressure': 1010.4479508196721,
        'rainfall': 2.6881147540983608},
       'Summer': {'avg_temp': 32.41353591160221,
        'min_temp': 27.269337016574585,
        'max_temp': 38.911878453038675,
        'wind_speed': 11.048066298342542,
        'air_pressure': 1005.296685082873,
        'rainfall': 1.9726519337016575},
       'Winter': {'avg_temp': 26.394263862332696,
        'min_temp': 20.597131931166345,
        'max_temp': 33.12275334608031,
        'wind_speed': 8.36959847036329,
        'air_pressure': 1012.376481835564,
        'rainfall': 0.5294455066921606}}}}},
   'Hanumakonda': {'avg_temp': 26.82726662189389,
    'min_temp': 22.21840161182001,
    'max_temp': 32.446138347884485,
    'wind_speed': 8.670718603089322,
    'air_pressure': 1008.8410342511753,
    'rainfall': 3.0871054398925453,
    'station_name': {'Hanamkonda': {'avg_temp': 26.82726662189389,
      'min_temp': 22.21840161182001,
      'max_temp': 32.446138347884485,
      'wind_speed': 8.670718603089322,
      'air_pressure': 1008.8410342511753,
      'rainfall': 3.0871054398925453,
      'season': {'Monsoon': {'avg_temp': 27.009166666666665,
        'min_temp': 24.320277777777775,
        'max_temp': 30.968611111111112,
        'wind_speed': 9.814444444444444,
        'air_pressure': 1004.483611111111,
        'rainfall': 9.26888888888889},
       'Post-monsoon': {'avg_temp': 25.236065573770492,
        'min_temp': 20.929918032786883,
        'max_temp': 30.54139344262295,
        'wind_speed': 7.160655737704918,
        'air_pressure': 1011.2459016393443,
        'rainfall': 1.465983606557377},
       'Summer': {'avg_temp': 30.951381215469613,
        'min_temp': 25.98453038674033,
        'max_temp': 37.07348066298343,
        'wind_speed': 9.474585635359116,
        'air_pressure': 1005.5773480662983,
        'rainfall': 2.0933701657458563},
       'Winter': {'avg_temp': 24.589866156787764,
        'min_temp': 18.765965583173998,
        'max_temp': 31.148948374760995,
        'wind_speed': 8.031548757170173,
        'air_pressure': 1012.9774378585086,
        'rainfall': 0.2760994263862333}}}}},
   'Hyderabad': {'avg_temp': 26.804331348132106,
    'min_temp': 21.374398108898557,
    'max_temp': 32.52606921889251,
    'wind_speed': 9.55268415663071,
    'air_pressure': 1011.067005979475,
    'rainfall': 3.2376593683673165,
    'station_name': {'Hyderabad / Anthredigudam': {'avg_temp': 26.33665403356795,
      'min_temp': 21.251639935672078,
      'max_temp': 31.867550029679776,
      'wind_speed': 11.508139365089706,
      'air_pressure': 1011.9423386343557,
      'rainfall': 3.0653950044979332,
      'season': {'Monsoon': {'avg_temp': 25.88,
        'min_temp': 22.816355787511036,
        'max_temp': 30.02016581175272,
        'wind_speed': 14.264497582475432,
        'air_pressure': 1008.1568469530296,
        'rainfall': 6.758955924135834},
       'Post-monsoon': {'avg_temp': 24.755081967213115,
        'min_temp': 19.944644658620067,
        'max_temp': 30.064876073380173,
        'wind_speed': 9.724888778041416,
        'air_pressure': 1014.0732240437158,
        'rainfall': 3.114469185587797},
       'Summer': {'avg_temp': 30.393406593406592,
        'min_temp': 24.79548368691671,
        'max_temp': 36.14520120284163,
        'wind_speed': 12.249719590396367,
        'air_pressure': 1009.3309009179533,
        'rainfall': 2.771993293844083},
       'Winter': {'avg_temp': 24.497129186602873,
        'min_temp': 18.16777288756782,
        'max_temp': 30.995589923027747,
        'wind_speed': 9.815232900237657,
        'air_pressure': 1015.5780807149272,
        'rainfall': 0.5446488004814408}}},
     'Hyderabad Airport': {'avg_temp': 27.272008662696265,
      'min_temp': 21.497156282125033,
      'max_temp': 33.18458840810524,
      'wind_speed': 7.597228948171712,
      'air_pressure': 1010.1916733245941,
      'rainfall': 3.409923732236699,
      'season': {'Monsoon': {'avg_temp': 26.42195652173913,
        'min_temp': 22.930541504325983,
        'max_temp': 31.46069054051158,
        'wind_speed': 9.70748594197437,
        'air_pressure': 1006.0918238170071,
        'rainfall': 7.414963478304093},
       'Post-monsoon': {'avg_temp': 25.61377049180328,
        'min_temp': 20.158745721491623,

In [21]:
data = {
    # dataset details
    "shape":df.shape,
    "columns": df.columns.tolist(),

    # unique values
    "season_values": df['season'].unique().tolist(),
    "station_count": df['station_name'].nunique(),
    # "state": df['state'].unique().tolist(),
    # "district": df.groupby('state')['district'].unique().apply(list).to_dict(),
    # "station": df.groupby('district')['station_name'].unique().apply(list).to_dict(),
    # "season": df.groupby('station_name')['season'].unique().apply(list).to_dict(),

    # missing value count
    "missing_values": missing_values,
    "null_count": null_count.to_dict(),

    "kpi_data": kpi_data,

    # mean values
    # "state_avg_temp": df.groupby('state')['avg_temp'].mean().to_dict(),
    # "district_avg_temp": district_groupwise_data('avg_temp'),
    # "station_avg_temp": station_groupwise_data('avg_temp'),
    # "season_avg_temp": season_groupwise_data('avg_temp'),
    # "state_min_temp": df.groupby('state')['min_temp'].mean().to_dict(),
    # "state_max_temp": df.groupby('state')['max_temp'].mean().to_dict(),
    # "state_wind_speed": df.groupby('state')['wind_speed'].mean().to_dict(),
    # "state_air_pressure": df.groupby('state')['air_pressure'].mean().to_dict(),
    # "state_rainfall": df.groupby('state')['rainfall'].mean().to_dict(),
    # "district_rainfall": district_groupwise_data('rainfall'),
    # "station_rainfall": station_groupwise_data('rainfall'),
    # "season_rainfall": season_groupwise_data('rainfall'),

    # time series trend analysis
    "avg_temp_time": [temp_series.index.astype(str).tolist(), temp_series.values.tolist()],
    "min_temp_time": [min_temp_series.index.astype(str).tolist(), min_temp_series.values.tolist()],
    "max_temp_time": [max_temp_series.index.astype(str).tolist(), max_temp_series.values.tolist()],
    "wind_speed_time": [wind_speed_series.index.astype(str).tolist(), wind_speed_series.values.tolist()],
    "air_pressure_time": [air_pressure_series.index.astype(str).tolist(), air_pressure_series.values.tolist()],
    "rainfall_time": [rainfall_series.index.astype(str).tolist(), rainfall_series.values.tolist()],

    # location analysis
    # "avg_temp_district": df.groupby('district')['avg_temp'].mean().to_dict(),
    # "avg_temp_station": df.groupby('station_name')['avg_temp'].mean().to_dict(),
    # "min_temp_district": df.groupby('district')['min_temp'].mean().to_dict(),
    # "min_temp_station": df.groupby('station_name')['min_temp'].mean().to_dict(),
    # "max_temp_district": df.groupby('district')['max_temp'].mean().to_dict(),
    # "max_temp_station": df.groupby('station_name')['max_temp'].mean().to_dict(),
    # "wind_speed_district": df.groupby('district')['wind_speed'].mean().to_dict(),
    # "wind_speed_station": df.groupby('station_name')['wind_speed'].mean().to_dict(),
    # "air_pressure_district": df.groupby('district')['air_pressure'].mean().to_dict(),
    # "air_pressure_station": df.groupby('station_name')['air_pressure'].mean().to_dict(),
    # "rainfall_district": df.groupby('district')['rainfall'].mean().to_dict(),
    # "rainfall_station": df.groupby('station_name')['rainfall'].mean().to_dict(),
    "avg_temp_lat_long" : df.groupby(['latitude','longitude']).agg({
        'avg_temp': 'mean',
        'min_temp': 'mean',
        'max_temp': 'mean',
        'wind_speed': 'mean',
        'air_pressure': 'mean',
        'rainfall': 'mean',
    }).reset_index().to_dict(orient='records'),
    "rainfall_lat_long": df.groupby(['latitude','longitude'])['rainfall'].mean().reset_index().to_dict(orient='records'),

    # distribution analysis
    "avg_temp_hist": {'count': np.histogram(df['avg_temp'], bins=1000)[0].tolist(), 'bins': np.histogram(df['avg_temp'], bins=1000)[1].tolist()},
    "min_temp_hist": {'count': np.histogram(df['min_temp'], bins=1000)[0].tolist(), 'bins': np.histogram(df['min_temp'], bins=1000)[1].tolist()},
    "max_temp_hist": {'count': np.histogram(df['max_temp'], bins=1000)[0].tolist(), 'bins': np.histogram(df['max_temp'], bins=1000)[1].tolist()},
    "wind_speed_hist": {'count': np.histogram(df['wind_speed'], bins=1000)[0].tolist(), 'bins': np.histogram(df['wind_speed'], bins=1000)[1].tolist()},
    "air_pressure_hist": {'count': np.histogram(df['air_pressure'], bins=1000)[0].tolist(), 'bins': np.histogram(df['air_pressure'], bins=1000)[1].tolist()},
    "rainfall_hist": {'count': np.histogram(df['rainfall'], bins=1000)[0].tolist(), 'bins': np.histogram(df['rainfall'], bins=1000)[1].tolist()},

    # outlier analysis
    "boxplot" : {
        "avg_temp": df_sample['avg_temp'].dropna().tolist(),
        "min_temp": df_sample['min_temp'].dropna().tolist(),
        "max_temp": df_sample['max_temp'].dropna().tolist(),
        "wind_speed": df_sample['wind_speed'].dropna().tolist(),
        "air_pressure": df_sample['air_pressure'].dropna().tolist(),
        "rainfall": df_sample['rainfall'].dropna().tolist(),
        "elevation": df_sample['elevation'].dropna().tolist(),
    },
    "outlier_stat": {
        "avg_temp": outlier_stats(df['avg_temp']),
        "min_temp": outlier_stats(df['min_temp']),
        "max_temp": outlier_stats(df['max_temp']),
        "wind_speed": outlier_stats(df['wind_speed']),
        "air_pressure": outlier_stats(df['air_pressure']),
        "rainfall": outlier_stats(df['rainfall'])
    },

    # scatter plot
    "scatter_sample": df_sample.to_dict(orient='records'),
    "scatter_sample_state": df_state_sample.to_dict(orient='records'),
    "scatter_sample_season": df_season_sample.to_dict(orient = 'records'),

    # correlation heatmap of numeric columns
    "corr": {
        'columns': corr.columns.tolist(),
        'values': corr.values.tolist()
    },

    # monthly trend
    "monthly_trend": monthly_trend.to_dict(orient='records'),

    # data stats
    'stats': stat,
}

In [23]:

with open('data.json', 'w') as f:
    json.dump(data, f, indent=4, default=str)

print("Data dumped successfully!")

Data dumped successfully!